import asyncio
import html
import logging
import smtplib
from abc import ABC, abstractmethod
from email.message import EmailMessage
from typing import Any, Optional

from fastapi import BackgroundTasks
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config.settings import settings
from app.core.database.postgres import async_session_maker
from app.models.email_log import EmailLog, EmailStatus
from app.repositories.email_log_repository import email_log_repository

logger = logging.getLogger(__name__)


class EmailProvider(ABC):
    @abstractmethod
    async def send(self, recipient_email: str, subject: str, html_body: str, text_body: str) -> None:
        raise NotImplementedError


class SMTPEmailProvider(EmailProvider):
    async def send(self, recipient_email: str, subject: str, html_body: str, text_body: str) -> None:
        def _send() -> None:
            msg = EmailMessage()
            msg["From"] = settings.MAIL_FROM
            msg["To"] = recipient_email
            msg["Subject"] = subject
            msg.set_content(text_body)
            msg.add_alternative(html_body, subtype="html")

            if settings.SMTP_USE_SSL:
                with smtplib.SMTP_SSL(settings.SMTP_HOST, settings.SMTP_PORT) as smtp:
                    if settings.SMTP_USERNAME:
                        smtp.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD or "")
                    smtp.send_message(msg)
            else:
                with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as smtp:
                    if settings.SMTP_USE_TLS:
                        smtp.starttls()
                    if settings.SMTP_USERNAME:
                        smtp.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD or "")
                    smtp.send_message(msg)

        await asyncio.to_thread(_send)


class ConsoleEmailProvider(EmailProvider):
    async def send(self, recipient_email: str, subject: str, html_body: str, text_body: str) -> None:
        logger.info("EMAIL[%s] %s", recipient_email, subject)
        logger.debug("%s", text_body)


class EmailService:
    def __init__(self) -> None:
        self.provider = self._build_provider()

    def _build_provider(self) -> EmailProvider:
        if settings.EMAIL_PROVIDER.lower() == "smtp":
            return SMTPEmailProvider()
        return ConsoleEmailProvider()

    def _render_html(self, template_name: str, context: dict[str, Any]) -> str:
        safe_context = {key: html.escape(str(value)) for key, value in context.items()}
        title = safe_context.get("title", "DVP Notification")
        body = safe_context.get("body", "")
        cta_text = safe_context.get("cta_text")
        cta_url = safe_context.get("cta_url")
        cta_html = f'<p><a href="{cta_url}" style="display:inline-block;padding:10px 16px;background:#0f172a;color:#fff;text-decoration:none;border-radius:8px;">{cta_text}</a></p>' if cta_text and cta_url else ""
        return f"""
        <html>
          <body style="font-family:Arial,sans-serif;line-height:1.6;color:#111827;">
            <div style="max-width:640px;margin:0 auto;padding:24px;">
              <h2>{title}</h2>
              <div>{body}</div>
              {cta_html}
              <p style="color:#6b7280;font-size:12px;">This message was generated by the DVP backend.</p>
            </div>
          </body>
        </html>
        """

    def _render_text(self, context: dict[str, Any]) -> str:
        return context.get("body", "")

    async def queue_email(
        self,
        db: AsyncSession,
        recipient_email: str,
        subject: str,
        template_name: str,
        context: dict[str, Any],
        background_tasks: Optional[BackgroundTasks] = None,
    ) -> EmailLog:
        log = await email_log_repository.create(
            db,
            obj_in={
                "recipient_email": recipient_email,
                "subject": subject,
                "template_name": template_name,
                "provider": settings.EMAIL_PROVIDER,
                "status": EmailStatus.QUEUED,
                "attempts": 0,
                "payload": context,
            },
        )

        from app.tasks.queue import enqueue_task
        from app.tasks.worker import send_email_job

        if background_tasks:
            await enqueue_task(background_tasks, send_email_job, email_log_id=log.id)
        else:
            try:
                await send_email_job({}, email_log_id=log.id)
            except Exception as exc:
                logger.warning("Inline email dispatch failed for log %s: %s", log.id, exc)

        return log

    async def send_email_by_log_id(self, db: AsyncSession, email_log_id: int) -> None:
        log = await email_log_repository.get(db, email_log_id)
        if not log:
            return

        payload = log.payload or {}
        html_body = self._render_html(log.template_name, payload)
        text_body = self._render_text(payload)
        await self.provider.send(log.recipient_email, log.subject, html_body, text_body)


email_service = EmailService()