"""add_employee_notes

Revision ID: 121541817f69
Revises: 0004_add_hr_role
Create Date: 2026-07-10 11:59:30.623141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121541817f69'
down_revision: Union[str, None] = '0004_add_hr_role'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'subscription_plan',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('companies', 'employee_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('companies', 'current_employee_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('companies', 'trial_used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('email_logs', 'provider',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('email_logs', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('employees', sa.Column('notes', sa.String(length=2000), nullable=True))
    op.drop_constraint(op.f('password_reset_tokens_token_key'), 'password_reset_tokens', type_='unique')
    op.alter_column('subscription_plans', 'max_admins',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_plans', 'max_employees',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_plans', 'monthly_document_uploads',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_plans', 'storage_mb',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_plans', 'chat_access',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_plans', 'api_access',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_plans', 'analytics_access',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_plans', 'ticket_priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_plans', 'white_label_support',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_plans', 'audit_log_retention_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_plans', 'billing_cycle_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_plans', 'trial_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_plans', 'price_cents',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_plans', 'is_custom',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('subscription_plans_code_key'), 'subscription_plans', type_='unique')
    op.alter_column('subscription_requests', 'immediate_effect',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_requests', 'prorated_value_cents',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_subscription_requests_company_id'), table_name='subscription_requests')
    op.alter_column('subscription_usage', 'employee_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_usage', 'monthly_document_uploads',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscription_usage', 'storage_used_bytes',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscriptions', 'plan_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('subscriptions', 'employee_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'trial_used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'must_change_password')
    op.alter_column('subscriptions', 'trial_used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('subscriptions', 'employee_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'plan_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('subscription_usage', 'storage_used_bytes',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.alter_column('subscription_usage', 'monthly_document_uploads',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('subscription_usage', 'employee_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_index(op.f('ix_subscription_requests_company_id'), 'subscription_requests', ['company_id'], unique=False)
    op.alter_column('subscription_requests', 'prorated_value_cents',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('subscription_requests', 'immediate_effect',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_unique_constraint(op.f('subscription_plans_code_key'), 'subscription_plans', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('subscription_plans', 'is_custom',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'price_cents',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'trial_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('14'),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'billing_cycle_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'audit_log_retention_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('90'),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'white_label_support',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'ticket_priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'LOW'::character varying"),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'analytics_access',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'api_access',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'chat_access',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'storage_mb',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1024'),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'monthly_document_uploads',
               existing_type=sa.INTEGER(),
               server_default=sa.text('100'),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'max_employees',
               existing_type=sa.INTEGER(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.alter_column('subscription_plans', 'max_admins',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.create_unique_constraint(op.f('password_reset_tokens_token_key'), 'password_reset_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('employees', 'notes')
    op.alter_column('email_logs', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('email_logs', 'provider',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'smtp'::character varying"),
               existing_nullable=False)
    op.alter_column('companies', 'trial_used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('companies', 'current_employee_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('companies', 'employee_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('companies', 'subscription_plan',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
