"""add_offer_joining_letter_fields

Revision ID: 319211993900
Revises: 121541817f69
Create Date: 2026-07-10 12:19:26.946540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319211993900'
down_revision: Union[str, None] = '121541817f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('offer_letter_url', sa.String(length=500), nullable=True))
    op.add_column('employees', sa.Column('joining_letter_url', sa.String(length=500), nullable=True))
    op.add_column('employees', sa.Column('letters_sent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'letters_sent')
    op.drop_column('employees', 'joining_letter_url')
    op.drop_column('employees', 'offer_letter_url')
    # ### end Alembic commands ###
